algoritmo "questão 1"

var
 numero1, numero2, resultado:real
 sair:caractere
inicio
Enquanto (sair <>"s")ou(sair <>"S") FACA

escreval ("escreva um numero para ser multiplicado:")
leia (numero1)
escreval ("escreva o segundo numero:")
leia (numero2)
resultado <- ( numero1 * numero2)
escreval(resultado)
 escreval("deseja sair S ou N? ")
 leia (sair)
 LIMPATELA
fimenquanto
fimalgoritmo
