Algoritmo "semnome"

Var
numero:real
Inicio
escreval("Escreva um numero para ver se ela se enquadra na questão")
leia (numero)
se (numero>22)entao
escreval("numero maior que 22")
senao
escreval("numero menor que 22")
fimse
se (numero>100)então
escreval("numero maior que 100")
senao
escreval("numero menor que 100")
fimse
se (numero = 55) então
escreval("numero igual a 55")
senao
escreval("numero diferente de 55")
fimse
Fimalgoritmo